[package]
name = "http-api-problem"
version = "0.16.0"
authors = ["Christian Douven <chridou@users.noreply.github.com>"]
description = "A library to create HTTP error response content for APIs based on RFC 7807"
repository = "https://github.com/chridou/http-api-problem"
homepage = "https://github.com/chridou/http-api-problem"
documentation = "https://docs.rs/http-api-problem"
readme = "README.md"
keywords = ["http", "api", "json", "error", "7807"]
categories = ["web-programming"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
http = { version = "0.2" }
hyper = { version = "0.13", optional = true }
actix-web = { version = "2.0", optional = true }
actix = { version = "0.9", optional = true }
failure = { version = "0.1", optional = true }
warp = { version = "0.2", optional = true, default-features = false }
rocket = { version = "0.4.2", optional = true }

[features]
default = []
with-actix-web = ["actix-web", "actix"]
with-hyper = ["hyper"]
with-warp = ["warp"]
with-failure = ["failure"]
with-api-error = []
with-rocket = ["rocket"]